prometheus:
  prometheusSpec:
    serviceMonitorSelectorNilUsesHelmValues: false
  service:
    type: NodePort
    nodePort: 30006    
grafana:
  service:
    type: NodePort
    nodePort: 30005
  dashboardProviders:
    dashboardproviders.yaml:
      apiVersion: 1
      providers:
        - name: 'kong'
          orgId: 1
          folder: 'Kong'
          type: file
          disableDeletion: true
          editable: true
          options:
            path: /var/lib/grafana/dashboards/kong
  dashboards:
    kong:
      kong-official:
        gnetId: 7424
        datasource: Prometheus
      kong-vitals:
        gnetId: 11870
        datasource: Prometheus