---
apiVersion: v1
kind: Namespace
metadata:
  name: httpbin-demo
---
apiVersion: configuration.konghq.com/v1
kind: KongConsumer
metadata:
  name: employee
  namespace: httpbin-demo
  annotations:
    kubernetes.io/ingress.class: kong
username: employee