---
apiVersion: configuration.konghq.com/v1
kind: KongPlugin
metadata:
  name: employee-rate-limiting
  namespace: default
plugin: rate-limiting
config:
  minute: 3
  policy: local
---
apiVersion: configuration.konghq.com/v1
kind: KongConsumer
metadata:
  name: employee
  annotations:
    kubernetes.io/ingress.class: kong
    konghq.com/plugins: "employee-rate-limiting"
username: employee