apiVersion: apps/v1
kind: Deployment
metadata:
  name: mockbin
  namespace: kong-dp
  labels:
    app: mockbin
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mockbin
  template:
    metadata:
      labels:
        app: mockbin
    spec:
      containers:
      - name: mockbin
        image: mashape/mockbin:latest
        ports:
        - name: http
          containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: mockbin
  namespace: kong-dp
  labels:
    app: mockbin
spec:
  ports:
  - name: http
    port: 8080
    targetPort: 8080
  selector:
    app: mockbin
  type: ClusterIP