---
apiVersion: v1
kind: Namespace
metadata:
  name: httpbin-demo
---
apiVersion: configuration.konghq.com/v1
kind: KongPlugin
metadata:
  name: httpbin-exit-transform
  namespace: httpbin-demo
  annotations:
    kubernetes.io/ingress.class: kong
config:
  functions:
  - |
    -- transform.lua
        return function(status, body, headers)
          if not body or not body.message then
            return status, body, headers
          end
          headers = { ["X-Some-Header"] = "ETP Triggered" }
          local new_body = {
            error = true,
            status = status,
            message = body.message .. ", Achtung!",
          }
          return status, new_body, headers\n
        end
#  - "-- transform.lua\n    return function(status, body, headers)\n      if not body or not body.message then\n        return status, body, headers\n      end\n      headers = { [\"X-Some-Header\"] = \"ETP Triggered\" }\n      local new_body = {\n        error = true,\n        status = status,\n        message = body.message .. \", Achtung!\",\n      }\n      return status, new_body, headers\n    end"
plugin: exit-transformer
---
apiVersion: v1
kind: Service
metadata:
  name: httpbin-service
  namespace: httpbin-demo
  annotations:
    konghq.com/path: "/anything"
    konghq.com/plugins: "httpbin-auth,httpbin-jq,httpbin-exit-transform"
spec:
  type: ExternalName
  externalName: httpbin.default.svc.cluster.local