---
apiVersion: v1
kind: Namespace
metadata:
  name: httpbin-demo
---
apiVersion: v1
kind: Service
metadata:
  name: redis-service
  namespace: httpbin-demo
spec:
  type: ExternalName
  externalName: redis
---
apiVersion: configuration.konghq.com/v1
kind: KongClusterPlugin
metadata:
  name: global-rate-limit-adv
  namespace: httpbin-demo
  annotations:
    kubernetes.io/ingress.class: kong
  labels:
    global: "true"
config:
  namespace: httpbin-demo
  limit: 
  - 10
  - 20
  window_size: 
  - 60
  - 90
  window_type: sliding
  sync_rate: 0
  strategy: redis
  redis:
    host: redis-service
    port: 6379
plugin: rate-limiting-advanced