---
apiVersion: v1
kind: Namespace
metadata:
  name: httpbin-demo
---
apiVersion: configuration.konghq.com/v1
kind: KongClusterPlugin
metadata:
  name: global-request-transform-adv
  namespace: httpbin-demo
  annotations:
    kubernetes.io/ingress.class: kong
  labels:
    global: "true"
config:
  add:
    headers:
    - X-Kong-Test-Request-Header:MyRequestHeader
  rename:
    headers:
    - User-Agent:My-User-Agent
plugin: request-transformer-advanced