---
apiVersion: v1
kind: Namespace
metadata:
  name: httpbin-demo
---
apiVersion: configuration.konghq.com/v1
kind: KongClusterPlugin
metadata:
  name: global-response-transform-adv
  namespace: httpbin-demo
  annotations:
    kubernetes.io/ingress.class: kong
  labels:
    global: "true"
config:
  add:
    json:
    - json-key-added:Test-Key
    headers:
    - X-Kong-Test-Response-Header:MyResponseHeader
plugin: response-transformer-advanced