# apiVersion: networking.k8s.io/v1
# kind: Ingress
# metadata:
#   name: keycloak-kong-ingress
#   namespace: kong
#   labels:
#     app.kubernetes.io/name: keycloak
#   annotations:
#     konghq.com/protocols: "https"
#     konghq.com/strip-path: "true"
#     konghq.com/preserve-host: "true"
#     kubernetes.io/ingress.class: "kong"
#     konghq.com/https-redirect-status-code: '302'
#     ingress.kubernetes.io/service-upstream: "true"
# spec:
#   tls:
#     - hosts:
#         - 30000-1-fc3eba47.labs.konghq.com
#       secretName: keycloak-tls
#   rules:
#   - host: keycloak.kong-dp.svc.cluster.local
#     http:
#       paths:
#       - path: /keycloak/*
#         pathType: Prefix
#         backend:
#           service:
#             name: keycloak
#             port:
#               name: keycloak
---
apiVersion: v1
kind: Service
metadata:
  name: keycloak
  namespace: kong-dp
  labels:
    app: keycloak
spec:
  ports:
  - name: http
    port: 8080
    targetPort: 8080
    nodePort: 30005
  selector:
    app: keycloak
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: keycloak
  namespace: kong-dp
  labels:
    app: keycloak
spec:
  replicas: 1
  selector:
    matchLabels:
      app: keycloak
  template:
    metadata:
      labels:
        app: keycloak
    spec:
      containers:
      - name: keycloak
        image: quay.io/keycloak/keycloak:17.0.1
        args: ["start-dev"]
        env:
        - name: KEYCLOAK_ADMIN
          value: "admin"
        - name: KEYCLOAK_ADMIN_PASSWORD
          value: "admin"
        - name: PROXY_ADDRESS_FORWARDING
          value: "true"
        - name: KEYCLOAK_URI
          value: https://30005-1-3ac87b1f.labs.konghq.com/
        - name: KEYCLOAK_HOSTNAME
          value: 30005-1-3ac87b1f.labs.konghq.com
        - name: KEYCLOAK_REDIRECT_URI
          value: https://30005-1-3ac87b1f.labs.konghq.com/
        - name: KEYCLOAK_CONFIG_ISSUER
          value: https://30005-1-3ac87b1f.labs.konghq.com/auth/realms/kong/.well-known/openid-configuration
        - name: KEYCLOAK_FRONTEND_URL
          value: https://30005-1-c0589a8a.labs.konghq.com/
        - name: KEYCLOAK_IMPORT
          valueFrom:
            secretKeyRef:
              name: keycloak-realm
              key: realm
        ports:
        - name: http
          containerPort: 8080
        readinessProbe:
          httpGet:
            path: /realms/master
            port: 8080