---
apiVersion: v1
kind: Namespace
metadata:
  name: httpbin-demo
---
apiVersion: configuration.konghq.com/v1
kind: KongPlugin
metadata:
  name: httpbin-auth
  namespace: httpbin-demo
plugin: key-auth
---
apiVersion: configuration.konghq.com/v1
kind: KongPlugin
metadata:
  name: httpbin-rate-limiting
  namespace:  httpbin-demo
plugin: rate-limiting
config:
  minute: 5
  policy: local
---
apiVersion: v1
kind: Service
metadata:
  name: httpbin-service
  namespace: httpbin-demo
  annotations:
    konghq.com/path: "/headers"
spec:
  type: ExternalName
  externalName: httpbin.default.svc.cluster.local
  annotations:
    konghq.com/plugins: "httpbin-auth,httpbin-rate-limiting"
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: httpbin
  namespace: httpbin-demo
  annotations: 
    konghq.com/strip-path: "true"
    konghq.com/plugins: "httpbin-auth,httpbin-rate-limiting"
spec:
  ingressClassName: kong
  rules:
  - http:
      paths:
      - path: /httpbin
        pathType: Prefix
        backend:
          service:
            name: httpbin-service
            port:
              number: 80