apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: admin-api-restrict
  namespace: kong
spec:
  podSelector:
    matchLabels:
      app: kong-kong
  policyTypes:
    - Ingress
  ingress:
    - from:
        - ipBlock:
            cidr: 172.16.0.0/12
        - ipBlock:
            cidr: 192.168.0.0/16
        - ipBlock:
            cidr: 10.0.0.0/8
      ports:
        - protocol: TCP
          port: 8001
