version: '2.2'

networks:
  kong-edu-net:
    name: kong-edu-net
    driver: bridge

services:
  keycloak:
    networks:
    - kong-edu-net
    image: jboss/keycloak:16.1.1
    container_name: keycloak
    command: -Dkeycloak.profile.feature.upload_scripts=enabled
    restart: on-failure
    ports:
    - 8080:8080
    environment:
      DB_VENDOR: H2
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: admin
      KEYCLOAK_IMPORT: ${HOME}/kong-course-gateway-ops-for-kubernetes/exercises/oidc/kong_realm_template.json
      PROXY_ADDRESS_FORWARDING: "true"
