apiVersion: v1
kind: Service
metadata:
  name: smtp-server
  namespace: kong-dp
  labels:
    app: smtp-server
spec:
  ports:
  - name: http
    port: 1025
    targetPort: 1025
  selector:
    app: smtp-server
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: smtp-server
  namespace: kong-dp
  labels:
    app: smtp-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: smtp-server
  template:
    metadata:
      labels:
        app: smtp-server
    spec:
      containers:
      - name: smtp-server
        image: reachfive/fake-smtp-server
        ports:
        - name: smtp
          containerPort: 1025
