---
apiVersion: configuration.konghq.com/v1
kind: KongConsumer
metadata:
  name: anonymous
  namespace: kong
  annotations:
    kubernetes.io/ingress.class: kong
username: anonymous
---
apiVersion: v1
kind: Secret
metadata:
  name: consa-pass
  namespace: kong
type: Opaque
data:
  password: a47abff985b7ec074df15ab8051abaf7359dba7c
---
apiVersion: configuration.konghq.com/v1
kind: KongConsumer
metadata:
  name: consa
  namespace: kong
  annotations:
    kubernetes.io/ingress.class: kong
username: consA
credentials:
  - consa-pass
---
apiVersion: v1
kind: Secret
metadata:
  name: consb-pass
  namespace: kong
type: Opaque
data:
  password: bc6786b6ac490c909ba91f9ae0e09c55913cf0dc
---
apiVersion: configuration.konghq.com/v1
kind: KongConsumer
metadata:
  name: consb
  namespace: kong
  annotations:
    kubernetes.io/ingress.class: kong
username: consB
credentials:
  - consb-pass
---
apiVersion: v1
kind: Secret
metadata:
  name: hmac-pass
  namespace: kong
type: Opaque
data:
  password: K1ngK0ng
---
apiVersion: configuration.konghq.com/v1
kind: KongConsumer
metadata:
  name: hmac-consumer
  namespace: kong
  annotations:
    kubernetes.io/ingress.class: kong
username: hmac-consumer
credentials:
  - hmac-pass
---
apiVersion: configuration.konghq.com/v1
kind: KongConsumer
metadata:
  name: oidc-consumer
  namespace: kong
  annotations:
    kubernetes.io/ingress.class: kong
custom_id: stu+keycloak_user@konghq.com
username: oidc-consumer