kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
name: multiverse
networking:
  apiServerAddress: ${KIND_HOST}
  apiServerPort: 8443
  disableDefaultCNI: true
  podSubnet: "192.168.0.0/16"
nodes:
  - role: control-plane
    extraPortMappings:
    - listenAddress: "0.0.0.0"
      protocol: TCP
      hostPort: 30000
      containerPort: 30000
    - listenAddress: "0.0.0.0"
      protocol: TCP
      hostPort: 30001
      containerPort: 30001
    - listenAddress: "0.0.0.0"
      protocol: TCP
      hostPort: 30002
      containerPort: 30002
    - listenAddress: "0.0.0.0"
      protocol: TCP
      hostPort: 30003
      containerPort: 30003
    - listenAddress: "0.0.0.0"
      protocol: TCP
      hostPort: 30004
      containerPort: 30004
    - listenAddress: "0.0.0.0"
      protocol: TCP
      hostPort: 30005
      containerPort: 30005
    - listenAddress: "0.0.0.0"
      protocol: TCP
      hostPort: 30006
      containerPort: 30006
    - listenAddress: "0.0.0.0"
      protocol: TCP
      hostPort: 30443
      containerPort: 30443
