---
apiVersion: v1
kind: Secret
metadata:
  name: jane-jwt
  namespace: kong-dp
type: Opaque
data:
  key: SmFuZVBhc3N3b3Jk
  kongCredType: a2V5LWF1dGg=
---
apiVersion: configuration.konghq.com/v1
kind: KongConsumer
metadata:
  name: jane
  namespace: kong-dp
  annotations:
    kubernetes.io/ingress.class: kong
username: jane
credentials:
  - jane-apikey