---
apiVersion: configuration.konghq.com/v1
kind: KongPlugin
metadata:
  name: httpbin-rate-limiting
  namespace: default
plugin: rate-limiting
config:
  minute: 5
---
apiVersion: configuration.konghq.com/v1
kind: KongConsumer
metadata:
  name: mtls-demo
  annotations:
    kubernetes.io/ingress.class: kong
    konghq.com/plugins: "httpbin-rate-limiting"
username: demo@example.com
credentials:
  - mtls-demo